import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: process.env.ADMIN_NAME,
      email: process.env.ADMIN_MAIL,
      password: bcrypt.hashSync(process.env.ADMIN_PASS),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Gigabyte GT 1030 2GB OC Graphics card',
      slug: 'gt 1030',
      category: 'Graphics card',
      image: '/images/gtx_1030-500x500.png',
      price: 90,
      brand: 'Gigabyte',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Get the ultimate gaming experience',
      isFeatured: true,
      banner: '/images/',
    },
    {
      name: 'BIOSTAR Radeon RX550 4GB GDDR5 Graphics Card',
      slug: 'radeon rx550',
      category: 'Graphics Card',
      image: '/images/radeon-rx550-01-500x500.webp',
      price: 90,
      brand: 'Radeon',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Get your ultimate gaming experience with Radeon',
      isFeatured: true,
      banner: '/images/',
    },
    {
      name: 'NVIDIA Quadro P1000 4GB GDDR5 Graphics Card',
      slug: 'Nvidia P1000',
      category: 'Graphics Card',
      image: '/images/quadro-p1000-02-500x500.webp',
      price: 150,
      brand: 'Nvidia',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Get the best gaming experience',
    },
    {
      name: 'In-Ear Headphones',
      slug: 'in-ear-headphones',
      category: 'Earphones',
      image: '/images/headphones_b_1.webp',
      price: 90,
      brand: 'Boat',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description:
        'Enjoy high-quality audio in a compact package with our In-Ear Headphones. These earphones fit snugly in your ears, providing a comfortable and secure fit while you listen to your favorite music or podcast. Perfect for daily use!',
    },

    {
      name: 'Colorful GeForce GTX 1650 NB 4GD6 V3-V 4GB GDDR6 Graphics Card',
      slug: 'gtx1650',
      category: 'Graphics Card',
      image: '/images/geforce-gtx-1650-nb-4gd6-v3-v-01-500x500.webp',
      price: 180,
      brand: 'Geforce',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Experience the future of gaming with our Gtx1650',
    },
    {
      name: 'Wireless C1',
      slug: 'Earphones',
      category: 'earphones',
      image: '/images/headphones_a_4.webp',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description:
        'Experience high-quality sound with our wireless earphones from Sony. These earphones are designed to provide a comfortable fit and a secure hold, making them perfect for workouts or commutes. With up to 15 hours of battery life and easy-to-use touch controls, you can enjoy your favorite music or take calls on the go. Our wireless earphones also come with a compact charging case that makes it easy to charge them on the go.',
    },
    {
      name: 'Asus Phoenix GeForce GTX 1050Ti 4GB GDDR5 Graphics Card',
      slug: 'gtx1050ti',
      category: 'Graphics Card',
      image: '/images/phoenix-gtx-1050ti-4gb-500x500.jpg',
      price: 180,
      brand: 'Asus',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Experience the future of gaming with our Gtx1050ti',
    },
  ],
};

export default data;
